# Generated by Django 3.2 on 2023-05-09 10:19
from django.utils import timezone


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(default=timezone.now().date()),
            preserve_default=False,
        ),
    ]
